export const practicumsEN = {
  sectionLabel: "Practicums",
  heading: "Structured",
  headingAccent: "Learning",
  body: "Our practicum program is designed to complement theoretical coursework with hands-on, real-world engineering experience.",
  sessions: "sessions",
  viewAll: "View All Practicums",
  items: [
    {
      code: "P01",
      title: "Telematics Workshop",
      icon: "📡",
      imageUrl: "",
      summary: "Foundations of telematics, PCB design, and ESP8266 development boards.",
      desc: "Introduces students to the fundamentals of telematics, from reading and drawing schematics through to laying out a printed circuit board. Students also get hands-on with 3D enclosure design in Fusion 360 before writing their first firmware for the ESP8266 development board.",
      sessions: "4",
      level: "",
      topics: ["Telematic Basics", "Schematic and PCB Design Basics", "3D Design Fusion 360 Basics", "ESP8266 Development Board"],
    },
    {
      code: "P02",
      title: "Digital Circuit",
      icon: "🔌",
      imageUrl: "",
      summary: "Combinational and sequential logic, from Karnaugh maps to counters.",
      desc: "Builds a solid grounding in digital logic design. Students work through decoders, multiplexers, and demultiplexers, learn to simplify Boolean expressions with Karnaugh maps, and finish by implementing sequential circuits such as registers and synchronous and asynchronous counters.",
      sessions: "5",
      level: "",
      topics: ["Digital Circuit Basics (Decoder, Demultiplexer, Multiplexer)", "Karnough Map Introduction", "Sequential Digital Circuit (Register, Synchronous Counter, and Asynchronous Counter)"],
    },
    {
      code: "P03",
      title: "Embedded Systems",
      icon: "🧩",
      imageUrl: "",
      summary: "Programming microcontrollers and interfacing with the physical world.",
      desc: "Still in development.",
      sessions: "-",
      level: "",
      topics: [],
    },
  ],
} as const;