export const practicumsID = {
  sectionLabel: "Praktikum",
  heading: "Pembelajaran",
  headingAccent: "Terstruktur",
  body: "Program praktikum kami dirancang untuk melengkapi perkuliahan teoritis dengan pengalaman rekayasa langsung di dunia nyata.",
  sessions: "sesi",
  viewAll: "Lihat Semua Praktikum",
  items: [
    {
      code: "P01",
      title: "Workshop Telematika",
      icon: "📡",
      imageUrl: "",
      summary: "Dasar-dasar telematika, desain PCB, dan board pengembangan ESP8266.",
      desc: "Memperkenalkan mahasiswa pada dasar-dasar telematika, mulai dari membaca dan menggambar skematik hingga menyusun tata letak papan sirkuit tercetak. Mahasiswa juga berlatih merancang enclosure 3D di Fusion 360 sebelum menulis firmware pertama mereka untuk board pengembangan ESP8266.",
      sessions: "4",
      level: "",
      topics: [
        { label: "Telematic Basics", url: "https://b401-robotics.github.io/modul-workshop-telematika/P1.pdf" },
        { label: "Schematic and PCB Design Basics", url: "https://b401-robotics.github.io/modul-workshop-telematika/P2.pdf" },
        { label: "3D Design Fusion 360 Basics", url: "https://b401-robotics.github.io/modul-workshop-telematika/P3.pdf" },
        { label: "ESP8266 Development Board", url: "https://b401-robotics.github.io/modul-workshop-telematika/P4.pdf" },
      ],
    },
    {
      code: "P02",
      title: "Rangkaian Digital",
      icon: "🔌",
      imageUrl: "",
      summary: "Logika kombinasional dan sekuensial, dari peta Karnaugh hingga counter.",
      desc: "Membangun dasar yang kuat dalam perancangan logika digital. Mahasiswa mempelajari decoder, multiplexer, dan demultiplexer, belajar menyederhanakan ekspresi Boolean dengan peta Karnaugh, dan diakhiri dengan mengimplementasikan rangkaian sekuensial seperti register serta counter sinkron dan asinkron.",
      sessions: "5",
      level: "",
      topics: [
        { label: "Dasar Rangkaian Digital", url: "https://drive.google.com/file/d/1c6oJ_MBw8AyEQRKVE_oYLuJ80ElkOYI0/view" },
        { label: "Decoder, Demux, dan Mux", url: "https://drive.google.com/file/d/1yUubh5EB3dNeRap2PpEHH5uczceIEywC/view" },
        { label: "Karnough Map", url: "https://drive.google.com/file/d/1eUIJqrdeyzwCrgwEnu0CaRmAmFVwJYKO/view" },
        { label: "Rangkaian Sequential", url: "https://drive.google.com/file/d/12TgRQAlvIZ-bSLmpTPcq0IeNOEu9LRjL/view" },
        { label: "Register and Counter", url: "https://drive.google.com/file/d/1S8-QqSwMwINfl79DC5JyAf5YzeXg5oUN/view?usp=drive_link" },
      ],
    },
    {
      code: "P03",
      title: "Sistem Tertanam",
      icon: "🧩",
      imageUrl: "",
      summary: "Pemrograman mikrokontroler dan antarmuka dengan dunia fisik.",
      desc: "Masih dalam pengembangan.",
      sessions: "-",
      level: "",
      topics: [],
    },
  ],
} as const;