export const equipmentID = {
  sectionLabel: "Fasilitas",
  heading: "Laboratorium",
  headingAccent: "Kami",
  body: "Laboratorium Robotika & Sistem Cerdas beroperasi di tiga ruangan khusus, masing-masing disiapkan untuk bagian pekerjaan kami yang berbeda — mulai dari manipulasi berat dan fabrikasi hingga prototipe tertanam, jaringan, dan pengembangan perangkat lunak.",
  facilitiesLabel: "Fasilitas di ruangan ini",
  clickForMoreInfo: "Klik untuk info lengkap",
  viewAll: "Lihat Semua Peralatan",
  labRooms: [
    {
      code: "TW2-901",
      name: "Laboratorium TW2-901",
      desc: "Lantai penelitian utama. Ruangan ini menampung lengan robot kolaboratif kami, platform robot bergerak, serta perangkat visi dan komputasi yang menggerakkannya. Sebagian besar proyek penelitian lab yang sedang berjalan dijalankan di sini, dan di sini pula eksperimen tugas akhir serta tesis mahasiswa disiapkan.",
      imageUrl: "",
      facilities: [
        {
          name: "Lengan Robot Kolaboratif UR5e",
          category: "Robotika",
          imageUrl: "",
          info: "Lengan robot kolaboratif 6-DOF dari Universal Robots dengan payload 5 kg dan jangkauan 850 mm. Digunakan untuk penelitian manipulasi, tugas pick-and-place, dan integrasi dengan pipeline visi. Mendukung driver ROS 2 dan force sensing berstandar keselamatan untuk eksperimen kolaborasi manusia-robot.",
        },
        {
          name: "Platform Bergerak Berbasis ROS 2",
          category: "Navigasi",
          imageUrl: "",
          info: "Basis bergerak differential-drive yang menjalankan ROS 2 Humble. Dilengkapi wheel encoder, IMU, dan lidar, digunakan untuk penelitian SLAM, perencanaan jalur, dan navigasi otonom. Mahasiswa menggunakannya untuk tugas kuliah dan demonstrasi tugas akhir.",
        },
        {
          name: "Kamera Kedalaman Intel RealSense",
          category: "Visi",
          imageUrl: "",
          info: "Kamera kedalaman D435i dan D455 yang menyediakan aliran RGB, depth, dan IMU. Digunakan untuk deteksi objek, estimasi pose, dan kalibrasi hand-eye pada lengan robot. Didukung di ROS 2 melalui paket realsense2_camera.",
        },
        {
          name: "GPU NVIDIA Seri Jetson",
          category: "Komputasi",
          imageUrl: "",
          info: "Modul komputasi edge Jetson Orin Nano dan Xavier NX. Digunakan untuk menjalankan beban persepsi dan inferensi langsung di robot, menjaga latensi tetap rendah. Mendukung CUDA, TensorRT, dan PyTorch untuk pembelajaran mesin on-device.",
        },
        {
          name: "Workstation Cetak 3D",
          category: "Prototipe",
          imageUrl: "",
          info: "Printer 3D FDM dengan kemampuan PLA, PETG, dan TPU. Digunakan untuk membuat bracket khusus, mount sensor, dan enclosure untuk proyek lab. Ukuran bed cetak 220 × 220 × 250 mm.",
        },
      ],
    },
    {
      code: "B401",
      name: "Laboratorium B401",
      desc: "Ruangan otomasi dan elektronika. Dilengkapi untuk bring-up perangkat keras, pekerjaan PCB, dan kendali pneumatik, ruangan ini mendukung sesi praktikum sekaligus pengembangan langsung proyek tertanam dan otomasi lab.",
      imageUrl: "",
      facilities: [
        {
          name: "Drone DJI Matrice 300 RTK",
          category: "UAV",
          imageUrl: "",
          info: "Platform quadcopter industrial dengan waktu terbang 55 menit dan rating IP45. Digunakan untuk pemetaan udara, penelitian inspeksi, dan eksperimen koordinasi multi-UAV. Mendukung positioning RTK untuk akurasi tingkat sentimeter.",
        },
        {
          name: "Sistem Pneumatik Festo",
          category: "Otomasi",
          imageUrl: "",
          info: "Aktuator pneumatik, valve, dan kontroler PLC yang digunakan untuk mengajar dan meneliti otomasi industri. Mendukung pemrograman ladder-logic dan integrasi dengan stack ROS 2 lab untuk proyek otomasi hibrida.",
        },
        {
          name: "Osiloskop & Penganalisis Sinyal",
          category: "Elektronika",
          imageUrl: "",
          info: "Osiloskop digital empat kanal hingga 200 MHz, plus logic analyzer untuk debugging protokol digital. Digunakan di semua sesi praktikum dan untuk bring-up perangkat keras pada proyek tertanam.",
        },
        {
          name: "Stasiun Soldering & Rework",
          category: "Elektronika",
          imageUrl: "",
          info: "Soldering iron bertemperatur terkontrol, stasiun rework hot-air, dan mikroskop stereo untuk pekerjaan SMD. Digunakan untuk merakit PCB khusus dan memperbaiki board untuk proyek yang sedang berjalan.",
        },
        {
          name: "Unit Catu Daya Bench",
          category: "Elektronika",
          imageUrl: "",
          info: "Catu daya DC yang dapat diprogram dengan batas tegangan dan arus yang dapat diatur. Digunakan untuk memberi daya prototipe selama pengembangan dan untuk mengkarakterisasi konsumsi daya pada perangkat bertenaga baterai.",
        },
      ],
    },
    {
      code: "A108",
      name: "Laboratorium A108",
      desc: "Ruangan komputasi dan jaringan. Berfokus pada perangkat lunak, sistem nirkabel, dan pengembangan tertanam, ruangan ini menjadi tempat sebagian besar pekerjaan IoT dan jaringan sensor nirkabel kami, bersama dengan pengembangan perangkat lunak dan simulasi umum.",
      imageUrl: "",
      facilities: [
        {
          name: "Workstation Desktop",
          category: "Komputasi",
          imageUrl: "",
          info: "Dua puluh workstation desktop berperforma tinggi dengan GPU diskrit, monitor ganda, dan penyimpanan jaringan bersama. Digunakan untuk pengembangan perangkat lunak, simulasi robotika di Gazebo dan Isaac Sim, serta pelatihan machine learning.",
        },
        {
          name: "Kit Gateway LoRaWAN",
          category: "Jaringan",
          imageUrl: "",
          info: "Gateway LoRaWAN multi-kanal dan modul end-device untuk penelitian komunikasi jarak jauh berdaya rendah. Digunakan dalam eksperimen lab dan lapangan untuk pemantauan pertanian dan lingkungan.",
        },
        {
          name: "Board Pengembangan Mikrokontroler",
          category: "Tertanam",
          imageUrl: "",
          info: "Beragam board pengembangan yang mencakup platform ESP32, ESP8266, STM32, dan Arduino. Digunakan dalam praktikum telematika dan sistem tertanam serta untuk prototipe perangkat keras baru dalam proyek lab.",
        },
        {
          name: "Kit Sensor (IMU, LiDAR, GPS)",
          category: "Sensor",
          imageUrl: "",
          info: "Berbagai sensor termasuk IMU 9-DOF, unit LiDAR 2D dan 3D, serta modul GPS berkapabilitas RTK. Digunakan untuk pengumpulan data, eksperimen kalibrasi, dan pengembangan algoritma fusi.",
        },
        {
          name: "Penganalisis Jaringan",
          category: "Jaringan",
          imageUrl: "",
          info: "Alat untuk memeriksa lalu lintas nirkabel dan mendiagnosis masalah jaringan. Digunakan untuk mengkarakterisasi perilaku LoRaWAN, Wi-Fi, dan BLE dalam penelitian jaringan lab.",
        },
      ],
    },
  ],
} as const;